spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xuzhuang1996/MyJava.git
          searchPaths: product-view-service-feign-dev  # searchPaths 表示目录：
      label: master # label 表示 分支：
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/